In [1]:
import matplotlib
matplotlib.use('Agg')
import pandas as pd
import seaborn as sns
import numpy as np


def boostrap(sample, sample_size, iterations):
    
    samples=np.zeros((iterations,sample_size))
    samples_means=np.zeros(iterations)
    print(samples_means)   
    print("Inicia for loop")
    for i in range(iterations):
        samples[i,:]=np.random.choice(sample,size=sample_size, replace=False)
        #print(samples)
        #print(np.mean(samples[i,:]))
        samples_means[i]=np.mean(samples[i,:])
        
        data_mean=np.mean(samples_means)
        
        np.sort(samples_means, axis=0)
        
        
        lower=np.percentile(samples_means,2.5)
        upper=np.percentile(samples_means,97.5)
        
    print("finaliza loop")
    print("Mean vector:")
    print(samples_means)
    
    return data_mean, lower, upper




if __name__ == "__main__":
    df = pd.read_csv('./salaries.csv')

    data = df.values.T[1]
    boots = []
    for i in range(100, 100000, 1000):
        boot = boostrap(data, data.shape[0], i)
        boots.append([i, boot[0], "mean"])
        boots.append([i, boot[1], "lower"])
        boots.append([i, boot[2], "upper"])

    df_boot = pd.DataFrame(boots, columns=['Boostrap Iterations', 'Mean', "Value"])
    sns_plot = sns.lmplot(df_boot.columns[0], df_boot.columns[1], data=df_boot, fit_reg=False, hue="Value")

    sns_plot.axes[0, 0].set_ylim(0,)
    sns_plot.axes[0, 0].set_xlim(0, 100000)

    sns_plot.savefig("bootstrap_confidence.png", bbox_inches='tight')
    sns_plot.savefig("bootstrap_confidence.pdf", bbox_inches='tight')


    #print ("Mean: %f")%(np.mean(data))
    #print ("Var: %f")%(np.var(data))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.52380952 42809.52380952
 42809.52380952 42809.52380952 42809.5238

finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[42809.52380952 42809.52380952 42809.52380952 ... 42809.52380952
 42809.52380952 42809.52380952]
[0. 0. 0. ... 0. 0. 0.]
Inicia for loop
finaliza loop
Me

KeyboardInterrupt: 

In [2]:
import matplotlib
matplotlib.use('Agg')
import pandas as pd
import seaborn as sns
import numpy as np
 

def boostrap(sample, sample_size, iterations):
    
    samples=np.zeros((iterations,sample_size))
    samples_means=np.zeros(iterations)
    print(samples_means)   
    print("Inicia for loop")
    for i in range(iterations):
        samples[i,:]=np.random.choice(sample,size=sample_size, replace=False)
        #print(samples)
        #print(np.mean(samples[i,:]))
        samples_means[i]=np.mean(samples[i,:])
        
        data_mean=np.mean(samples_means)
        
        np.sort(samples_means, axis=0)
        
        
        lower=np.percentile(samples_means,2.5)
        upper=np.percentile(samples_means,97.5)
        
    print("finaliza loop")
    print("Mean vector:")
    print(samples_means)
    
    return data_mean, lower, upper

In [3]:
test1=np.array(([1,2,3],[3,4,5],[2,4,5]))
data_test = pd.DataFrame({'Column1':test1[:,0],'Column2':test1[:,1]})
print(data_test)

test_2=np.array([1,2,3,4,5,6,7,8])


   Column1  Column2
0        1        2
1        3        4
2        2        4


In [4]:
boostrap(test_2,5,10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Inicia for loop
finaliza loop
Mean vector:
[5.  4.4 4.2 4.6 5.4 3.  5.4 4.6 4.8 5. ]


(4.64, 3.2700000000000005, 5.4)

In [5]:
df

Employee ID    Salary
0             1   10000.0
1             2  100000.0
2             3  200000.0
3             4  140000.0
4             5   12000.0
5             6   13000.0
6             7  140000.0
7             8   15000.0
8             9  120000.0
9            10   11000.0
10           11    8000.0
11           12    9000.0
12           13   14000.0
13           14   14000.0
14           15    5000.0
15           16   18000.0
16           17    6000.0
17           18   18000.0
18           19   15000.0
19           20   19000.0
20           21   12000.0